"""Per-card worktree + verification capture.

Real HTTP dispatch binds an operator-PREPARED worktree: the dispatcher
validates it (right repo, HEAD == pinned base, clean) and validates the
protected Runner execution config binds the submitted ``workspace_id`` to
exactly that path. An autogenerated worktree under ``worktree_root`` exists
only behind the explicit ``allow_ephemeral_worktree`` development flag.

Dependencies must prove their ``integrated_revision`` is an ancestor of the
base — a ``done`` status alone is never sufficient. All subprocesses are
argv lists; no shell strings. Verification runs in its own process group
with bounded output drain, so a timeout kills stubborn children too.
"""

from __future__ import annotations

import fnmatch
import hashlib
import json
import os
import re
import signal
import stat
import subprocess
import threading
from dataclasses import dataclass, field
from pathlib import Path

_FULL_COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")
_BRANCH_SAFE = re.compile(r"[^A-Za-z0-9_-]")

# The Runner's cross-process claim record lives inside the bound root; it is
# infra bookkeeping, not card output, so it never counts as a scope change.
_RUNNER_LOCK_NAME = ".cli-provider-runner.lock"

# Mirrors cli_provider_runner.execution_config (kanban cannot import the
# Runner package — same explicit shape, validated independently).
_RUNNER_CONFIG_MAX_BYTES = 65536
_RUNNER_KNOWN_ACTIONS = frozenset(
    {"hermes.yolo", "devin.acp.session_mode.bypass"}
)

# Generic secret-shaped output patterns; configured credential VALUES are
# redacted separately (literal match) by the caller.
_BEARER_RE = re.compile(r"Bearer\s+[A-Za-z0-9._\-+/=]{8,}")
_KEY_VALUE_RE = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|passwd)"
    r"(=|:|\s+is\s+)['\"]?[^\s'\"]{8,}"
)
_SCOPE_CHARS = re.compile(r"^[A-Za-z0-9_\-./\*\?\[\]{}!]+$")


class WorktreeError(Exception):
    """Trusted-workspace or git precondition failure (fail-closed)."""


@dataclass(frozen=True)
class Worktree:
    path: Path
    branch: str | None      # None = detached HEAD
    base_revision: str
    workspace_id: str


@dataclass(frozen=True)
class VerifyResult:
    ok: bool
    exit_code: int | None
    output: str            # bounded tail
    truncated: bool
    timed_out: bool = False


@dataclass(frozen=True)
class DepCheck:
    task_id: str
    ok: bool
    reason: str | None = None
    integrated_revision: str | None = None


def _git(repo: Path, *argv: str, check: bool = True,
         capture: bool = True, timeout: float = 60.0) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        ["git", "-C", str(repo), *argv],
        capture_output=capture,
        text=True,
        timeout=timeout,
    )
    if check and proc.returncode != 0:
        raise WorktreeError(
            f"git {' '.join(argv[:2])} failed in {repo}: "
            f"{(proc.stderr or proc.stdout or '').strip()[:400]}"
        )
    return proc


def validate_commit(rev: str) -> str:
    """Full 40-hex commit only — never a ref, range, or arbitrary string."""
    if not _FULL_COMMIT_RE.match(rev or ""):
        raise WorktreeError(
            f"base/integrated revision {rev!r} is not a full 40-hex commit"
        )
    return rev


def resolve_repo(repo: str) -> Path:
    """The configured repo must be a real git repository (fail-closed)."""
    root = Path(repo).resolve()
    if not root.is_dir():
        raise WorktreeError(f"workspace repo {repo!r} does not exist")
    probe = _git(root, "rev-parse", "--git-dir", check=False)
    if probe.returncode != 0:
        raise WorktreeError(f"workspace repo {repo!r} is not a git repository")
    return root


def assert_is_ancestor(repo: Path, rev: str, base: str) -> None:
    """``rev`` must already be contained in ``base`` (dependency integrated)."""
    proc = _git(
        repo, "merge-base", "--is-ancestor", rev, base, check=False,
    )
    if proc.returncode != 0:
        raise WorktreeError(
            f"integrated revision {rev[:12]} is not an ancestor of "
            f"base {base[:12]}"
        )


def check_dependencies(
    repo: Path,
    base_revision: str,
    deps: list[tuple[str, str | None]],
) -> list[DepCheck]:
    """``deps`` = (task_id, integrated_revision-or-None). Every dependency
    must carry a recorded integrated_revision that is an ancestor of base."""
    out: list[DepCheck] = []
    for task_id, rev in deps:
        if not rev:
            out.append(DepCheck(task_id, False, "no integrated_revision recorded"))
            continue
        try:
            validate_commit(rev)
            assert_is_ancestor(repo, rev, base_revision)
            out.append(DepCheck(task_id, True, integrated_revision=rev))
        except WorktreeError as exc:
            out.append(DepCheck(task_id, False, str(exc), rev))
    return out


def branch_name(dispatch_id: str) -> str:
    return "jev/" + _BRANCH_SAFE.sub("-", dispatch_id)


def _git_dir_of(path: Path) -> Path:
    """Canonical common git dir for a repo/worktree path."""
    proc = _git(path, "rev-parse", "--git-common-dir")
    raw = proc.stdout.strip()
    common = Path(raw)
    if not common.is_absolute():
        common = path / common
    return common.resolve()


def validate_prepared_worktree(
    *,
    repo: Path,
    prepared: str,
    base_revision: str,
    workspace_id: str,
) -> Worktree:
    """Admit the operator-prepared worktree — fail closed on any mismatch.

    The prepared path must be a real git worktree of the approved ``repo``,
    checked out at exactly ``base_revision``, in a clean state. We never
    mutate it into compliance: foreign/dirty state is preserved untouched.
    """
    validate_commit(base_revision)
    path = Path(prepared)
    if not path.is_dir():
        raise WorktreeError(
            f"prepared worktree {prepared!r} does not exist — the operator "
            "must create it before this card can dispatch"
        )
    canonical = path.resolve()
    probe = _git(canonical, "rev-parse", "--git-common-dir", check=False)
    if probe.returncode != 0:
        raise WorktreeError(
            f"prepared worktree {prepared!r} is not a git worktree"
        )
    if _git_dir_of(canonical) != _git_dir_of(repo):
        raise WorktreeError(
            f"prepared worktree {prepared!r} belongs to a different "
            "repository than the approved workspace repo"
        )
    head = _git(canonical, "rev-parse", "HEAD").stdout.strip()
    if head != base_revision:
        raise WorktreeError(
            f"prepared worktree HEAD {head[:12]} != pinned base "
            f"{base_revision[:12]} — refusing to run against the wrong "
            "revision"
        )
    dirty = _git(canonical, "status", "--porcelain").stdout
    dirty = "\n".join(
        line for line in dirty.splitlines()
        if line.strip() and _RUNNER_LOCK_NAME not in line
    ).strip()
    if dirty:
        raise WorktreeError(
            "prepared worktree is not clean — refusing to run on top of "
            f"unexpected changes ({dirty.splitlines()[0][:80]}…); the "
            "existing state is preserved, reset it deliberately"
        )
    branch = _git(
        canonical, "branch", "--show-current", check=False
    ).stdout.strip() or None
    return Worktree(
        path=canonical, branch=branch, base_revision=base_revision,
        workspace_id=workspace_id,
    )


def _check_runner_file_trusted(path: str) -> Path:
    """Same trust bar as the Runner's own loader: canonical path, regular
    file owned by this uid, 0600/0640, private parent directory."""
    absolute = os.path.abspath(path)
    canonical = os.path.realpath(absolute)
    if canonical != absolute:
        raise WorktreeError(
            "runner execution config path must be canonical — no symlink "
            "components"
        )
    try:
        st = os.lstat(canonical)
    except OSError as exc:
        raise WorktreeError(
            f"runner execution config is not readable: {type(exc).__name__}"
        )
    if not stat.S_ISREG(st.st_mode):
        raise WorktreeError("runner execution config must be a regular file")
    euid = os.geteuid()
    if st.st_uid != euid:
        raise WorktreeError(
            "runner execution config must be owned by this uid"
        )
    if st.st_mode & 0o137:
        raise WorktreeError(
            "runner execution config permissions must be 0600 or 0640"
        )
    parent = os.path.dirname(canonical)
    pst = os.lstat(parent)
    if not stat.S_ISDIR(pst.st_mode) or pst.st_uid != euid or (
        pst.st_mode & 0o077
    ):
        raise WorktreeError(
            "runner execution config parent directory must be private "
            "(owned, 0700)"
        )
    return Path(canonical)


def validate_runner_binding(
    *,
    config_path: str,
    workspace_id: str,
    prepared_path: str,
    submitted_model: str,
    candidate_models: list[str] | None = None,
) -> dict:
    """Prove the protected Runner config binds ``workspace_id`` to exactly
    the prepared worktree and permits the submitted model.

    Same explicit JSON shape the Runner loader validates (version=1,
    workspaces -> {root, allowed_actions, allowed_presets, allowed_models});
    validated independently because kanban cannot import the Runner package.
    """
    canonical = _check_runner_file_trusted(config_path)
    raw = canonical.read_bytes()
    if len(raw) > _RUNNER_CONFIG_MAX_BYTES:
        raise WorktreeError("runner execution config exceeds 64 KiB")
    try:
        data = json.loads(raw.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise WorktreeError(f"runner execution config is not JSON: {exc}")
    if not isinstance(data, dict) or data.get("version") != 1:
        raise WorktreeError("runner execution config must be version 1")
    workspaces = data.get("workspaces")
    if not isinstance(workspaces, dict):
        raise WorktreeError("runner execution config lacks workspaces map")
    binding = workspaces.get(workspace_id)
    if not isinstance(binding, dict):
        raise WorktreeError(
            f"runner execution config has no binding for workspace "
            f"{workspace_id!r} — the submitted id resolves nowhere"
        )
    allowed_keys = {
        "root", "allowed_actions", "allowed_presets", "allowed_models"
    }
    unknown_keys = set(binding) - allowed_keys
    if unknown_keys:
        raise WorktreeError(
            f"runner binding carries unknown keys {sorted(unknown_keys)}"
        )
    root = binding.get("root")
    if not isinstance(root, str) or not os.path.isabs(root):
        raise WorktreeError("runner binding root must be an absolute path")
    if os.path.realpath(root) != os.path.realpath(prepared_path):
        raise WorktreeError(
            f"runner binding root {root!r} does not equal the prepared "
            f"worktree {prepared_path!r} — the run would land in the wrong "
            "directory"
        )
    actions = binding.get("allowed_actions") or []
    if not isinstance(actions, list) or any(
        a not in _RUNNER_KNOWN_ACTIONS for a in actions
    ):
        raise WorktreeError(
            "runner binding grants unknown allowed_actions — the Runner "
            "itself would reject this config"
        )
    presets = binding.get("allowed_presets")
    if presets is not None:
        if not isinstance(presets, list) or submitted_model not in presets:
            raise WorktreeError(
                f"runner binding does not allow preset {submitted_model!r} "
                f"on workspace {workspace_id!r}"
            )
    models = binding.get("allowed_models")
    if models is not None:
        if not isinstance(models, list):
            raise WorktreeError("runner binding allowed_models must be a list")
        for desc in candidate_models or []:
            if desc not in models:
                raise WorktreeError(
                    f"runner binding does not allow model {desc!r} on "
                    f"workspace {workspace_id!r}"
                )
    return binding


def prepare_worktree(
    *,
    repo: Path,
    worktree_root: Path,
    workspace_id: str,
    dispatch_id: str,
    base_revision: str,
) -> Worktree:
    """Create the deterministic per-card worktree at the pinned base."""
    validate_commit(base_revision)
    # Confirm the pinned base actually exists in the trusted repo.
    _git(repo, "cat-file", "-e", f"{base_revision}^{{commit}}")

    root = Path(worktree_root)
    root.mkdir(parents=True, exist_ok=True)
    wt_path = (root / dispatch_id).resolve()
    if not str(wt_path).startswith(str(root.resolve()) + os.sep):
        raise WorktreeError(f"worktree path escapes root: {wt_path}")
    branch = branch_name(dispatch_id)
    proc = _git(
        repo,
        "worktree", "add", "--detach", str(wt_path), base_revision,
        check=False,
    )
    if proc.returncode != 0:
        raise WorktreeError(
            f"git worktree add failed: {(proc.stderr or '').strip()[:400]}"
        )
    # Named branch for the card's commits, still at the pinned base.
    _git(wt_path, "checkout", "-B", branch)
    return Worktree(
        path=wt_path, branch=branch, base_revision=base_revision,
        workspace_id=workspace_id,
    )


def _resolve_in_root(root: Path, rel: str) -> Path:
    """Card-declared relative path -> absolute, confined to ``root`` and
    rejecting symlink escapes."""
    if not rel or rel.startswith("/") or rel.startswith("~"):
        raise WorktreeError(f"path {rel!r} must be workspace-relative")
    candidate = (root / rel).resolve()
    resolved_root = root.resolve()
    if candidate != resolved_root and resolved_root not in candidate.parents:
        raise WorktreeError(
            f"path {rel!r} resolves outside the worktree root"
        )
    return candidate


def capture_diff(wt: Worktree, max_bytes: int) -> str:
    """Bounded ``git diff`` of the worktree against the pinned base.

    Covers BOTH committed work on the card branch AND dirty/untracked state:
    ``add -N`` records intent for untracked files and ``diff <base>``
    compares the base against the whole working tree, so a committed file
    plus a dirty edit both appear.
    """
    _git(wt.path, "add", "-N", ".", check=False, timeout=60)
    proc = _git(wt.path, "diff", "--binary", wt.base_revision,
                check=False, timeout=120)
    out = proc.stdout or ""
    if len(out.encode("utf-8", "replace")) > max_bytes:
        out = out.encode("utf-8", "replace")[:max_bytes].decode(
            "utf-8", "replace"
        ) + "\n[diff truncated]\n"
    return out


def changed_files(wt: Worktree) -> list[str]:
    """All paths that differ from the pinned base — committed, dirty, and
    untracked (via intent-to-add). The Runner's lock file is excluded: it is
    infra bookkeeping inside the bound root, not card output."""
    _git(wt.path, "add", "-N", ".", check=False, timeout=60)
    proc = _git(wt.path, "diff", "--name-only", wt.base_revision,
                check=False, timeout=120)
    names = {
        line.strip() for line in (proc.stdout or "").splitlines()
        if line.strip()
    }
    names.discard(_RUNNER_LOCK_NAME)
    return sorted(names)


def _scope_entry_enforceable(entry: str) -> bool:
    """A scope entry must be a clean relative path, dir prefix, or glob —
    natural-language scope cannot be enforced and fails closed."""
    if not entry or entry.startswith("/") or ".." in entry.split("/"):
        return False
    return bool(_SCOPE_CHARS.match(entry))


def _scope_entry_matches(entry: str, relpath: str) -> bool:
    if entry.endswith("/"):
        return relpath.startswith(entry)
    if any(ch in entry for ch in "*?["):
        return fnmatch.fnmatch(relpath, entry)
    return relpath == entry


def check_scope(changed: list[str], allowed_scope: list[str]) -> list[str]:
    """Changed files that fall outside every allowed-scope entry.

    An unenforceable entry (natural language, absolute, traversal) cannot
    grant anything — every changed file violates the scope then. Fail
    closed, no guessed parser.
    """
    if not changed:
        return []
    enforceable = [e for e in allowed_scope if _scope_entry_enforceable(e)]
    violations = []
    for rel in changed:
        if not any(_scope_entry_matches(e, rel) for e in enforceable):
            violations.append(rel)
    return violations


def sanitize_text(text: str, secrets: list[str] | tuple[str, ...] = ()) -> str:
    """Redact known credential values and common secret shapes before any
    durable storage or Kanban metadata write."""
    out = text
    for value in secrets:
        if value:
            out = out.replace(value, "[REDACTED]")
    out = _BEARER_RE.sub("Bearer [REDACTED]", out)
    out = _KEY_VALUE_RE.sub(
        lambda m: m.group(1) + m.group(2) + "[REDACTED]", out
    )
    return out


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path, *, max_bytes: int) -> tuple[str, int]:
    """(hex digest, size) for a file at most ``max_bytes`` — oversize is a
    caller-side refusal, never a silent hash of a prefix."""
    st = path.stat()
    if st.st_size > max_bytes:
        raise WorktreeError(
            f"artifact {path} exceeds {max_bytes} bytes — not hashing a "
            "partial read"
        )
    return sha256_bytes(path.read_bytes()), st.st_size


def collect_artifacts(
    wt: Worktree, artifact_paths: list[str], *, max_bytes: int
) -> tuple[list[Path], list[str]]:
    """Return (collected, missing). Missing artifacts are a typed failure —
    the caller blocks ``quality_failed``, never falls back."""
    collected: list[Path] = []
    missing: list[str] = []
    for rel in artifact_paths:
        target = _resolve_in_root(wt.path, rel)
        if not target.is_file():
            missing.append(rel)
            continue
        if target.stat().st_size > max_bytes:
            missing.append(f"{rel} (exceeds {max_bytes} bytes)")
            continue
        collected.append(target)
    return collected, missing


def _resolve_argv0(argv0: str, executables: dict[str, str]) -> str | None:
    """argv[0] -> executable path: absolute as-is, else basename -> the
    policy's ``executables`` map. Anything else cannot resolve."""
    if os.path.isabs(argv0):
        return argv0
    return executables.get(Path(argv0).name)


def _argv_allowed(
    argv: list[str],
    *,
    executables: dict[str, str],
    commands: list[list[str]],
) -> str | None:
    """Match the FULL argv against the operator-trusted ``commands``
    allowlist (element-for-element after argv[0] resolution; a trailing
    ``"*"`` matches any tail). Returns the resolved argv or None."""
    if not argv:
        return None
    head = _resolve_argv0(str(argv[0]), executables)
    if head is None:
        return None
    resolved = [head, *[str(a) for a in argv[1:]]]
    for entry in commands:
        if not entry:
            continue
        ehead = _resolve_argv0(str(entry[0]), executables)
        if ehead is None:
            continue
        pat = [ehead, *[str(a) for a in entry[1:]]]
        if pat[-1] == "*":
            if resolved[: len(pat) - 1] == pat[:-1]:
                return resolved
        elif resolved == pat:
            return resolved
    return None


def _drain(stream, sink: bytearray, state: dict, cap: int) -> None:
    """Read the stream to EOF, keeping a bounded tail — ``state["retained"]``
    is shared across stdout/stderr so the CAP IS TOTAL, not per-stream; the
    drain must never stop early or the child would block on a full pipe."""
    try:
        while True:
            chunk = stream.read(65536)
            if not chunk:
                return
            state["seen"] += len(chunk)
            room = cap - state["retained"]
            if room > 0:
                keep = chunk[:room]
                sink += keep
                state["retained"] += len(keep)
    except (OSError, ValueError):
        return


def run_verification(
    wt: Worktree,
    argv: list[str],
    *,
    executables: dict[str, str],
    commands: list[list[str]],
    timeout_seconds: float,
    max_output_bytes: int,
) -> VerifyResult:
    """Run the card's declared verification argv — full-argv allowlist only,
    argv array (never a shell string), bounded capture, and a process-group
    kill on timeout so stubborn children die with the leader."""
    resolved = _argv_allowed(argv, executables=executables, commands=commands)
    if resolved is None:
        shown = " ".join(str(a) for a in argv)[:200] if argv else "<empty>"
        return VerifyResult(
            ok=False, exit_code=None,
            output=(
                f"verification argv {shown!r} is not allowed — the policy "
                "verification.commands allowlist pins the full argv"
            ),
            truncated=False,
        )
    out_buf = bytearray()
    err_buf = bytearray()
    state = {"seen": 0, "retained": 0}
    try:
        proc = subprocess.Popen(
            resolved, cwd=str(wt.path),
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            start_new_session=True,   # own process group — killable whole
        )
    except OSError as exc:
        return VerifyResult(ok=False, exit_code=None,
                            output=f"spawn failed: {exc}", truncated=False)
    threads = [
        threading.Thread(target=_drain,
                         args=(proc.stdout, out_buf, state, max_output_bytes),
                         daemon=True),
        threading.Thread(target=_drain,
                         args=(proc.stderr, err_buf, state, max_output_bytes),
                         daemon=True),
    ]
    for t in threads:
        t.start()
    timed_out = False
    try:
        proc.wait(timeout=timeout_seconds)
    except subprocess.TimeoutExpired:
        timed_out = True
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass
        proc.wait(timeout=10)
    for t in threads:
        t.join(timeout=10)
    output = (out_buf + b"\n" + err_buf).decode("utf-8", "replace").strip()
    truncated = state["seen"] > state["retained"]
    if truncated:
        output += "\n[output truncated]"
    return VerifyResult(
        ok=proc.returncode == 0 and not timed_out,
        exit_code=None if timed_out else proc.returncode,
        output=output, truncated=truncated, timed_out=timed_out,
    )


def remove_worktree(wt: Worktree, repo: Path) -> None:
    """Best-effort cleanup — partial worktrees are preserved on error paths,
    so this is only called on explicit success/cancel teardown."""
    subprocess.run(
        ["git", "-C", str(repo), "worktree", "remove", "--force", str(wt.path)],
        capture_output=True, timeout=60,
    )
