"""Workspace admission — real HTTP dispatch must bind a PREPARED worktree.

The parent-identified defect: the dispatcher created a random worktree but
submitted a fixed ``wrapper_workspace_id`` that the Runner binds to a static
configured root — the run executed against an unrelated directory. The fix:
production workspaces carry an operator-prepared worktree plus the Runner
execution config that binds the submitted workspace id to exactly that path;
anything else fails closed BEFORE any HTTP request.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from cli_provider_kanban.dispatch import dispatch_once
from cli_provider_kanban.store import DispatchStore

from conftest import (  # noqa: F401
    CURRENT_OS_USER,
    FakeWrapper,
    dispatch_policy,
    make_prepared_worktree,
    policy_dict,
    requires_hermes,
    spec_dict,
    write_policy,
    write_runner_config,
)
from test_dispatch import HERMES_ENV_KEYS, _spec_for, board  # noqa: F401

pytestmark = requires_hermes


def _card(bridge, tmp_path, data, rev, **spec_over):
    tid = bridge.call("create_task", title="c", assignee="jev-native",
                      body="x")["task_id"]
    spec = _spec_for(tid, rev, **spec_over)
    del spec["task_id"]
    tm = tmp_path / f"tm_{tid}.json"
    tm.write_text(json.dumps({tid: spec}))
    data["task_map"] = str(tm)
    return tid


def _run(board, tmp_path, data, client=None):
    policy_path = write_policy(tmp_path, data)
    store = tmp_path / "dispatch.db"
    report = dispatch_once(
        board_db=board, policy_path=policy_path, store_path=store,
        client=client or FakeWrapper(),
    )
    return report, store


def _result(report, tid):
    return next(r for r in report["results"] if r["task_id"] == tid)


def test_prepared_worktree_dispatches(board, tmp_path, dispatch_policy):
    """Happy path: prepared worktree + matching binding -> submit + review."""
    db, bridge = board
    data, rev = dispatch_policy
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, store = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "review", rec
    assert len(client.calls) == 1
    # The submitted workspace id is the bound wrapper id, and the receipt
    # records the prepared path (not an autogenerated one).
    assert client.calls[0]["workspace_id"] == "ws-alpha"
    receipt = DispatchStore(store).for_task(tid)[0]
    assert receipt.worktree == data["workspaces"]["ws-main"]["prepared_worktree"]


def test_no_prepared_binding_fails_closed_before_http(
    board, tmp_path, dispatch_policy
):
    """A workspace with no prepared worktree and no explicit mock opt-in must
    refuse BEFORE any HTTP — never submit an unbound autogenerated root."""
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    ws.pop("prepared_worktree")
    ws.pop("runner_execution_config")
    ws.pop("worktree_root", None)
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, store = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []  # nothing reached the wire
    assert bridge.call("get_task", task_id=tid)["task"]["status"] == "blocked"


def test_ephemeral_worktree_is_explicit_mock_only(
    board, tmp_path, dispatch_policy
):
    """Autogenerated worktrees remain possible only via the explicit
    development flag — and the report must label the path synthetic."""
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    ws.pop("prepared_worktree")
    ws.pop("runner_execution_config")
    ws["allow_ephemeral_worktree"] = True
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, store = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "review", rec
    assert rec.get("synthetic") is True or rec.get("ephemeral") is True


def test_prepared_worktree_at_wrong_revision_refused(
    board, tmp_path, dispatch_policy
):
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    repo = ws["repo"]
    # Advance the repo and prepare a worktree at the NEW commit while the
    # card pins the OLD base -> HEAD != base must refuse.
    env = dict(os.environ, GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t",
               GIT_COMMITTER_NAME="t", GIT_COMMITTER_EMAIL="t@t")
    Path(repo, "later.txt").write_text("later\n")
    subprocess.run(["git", "add", "-A"], cwd=repo, env=env, check=True,
                   capture_output=True)
    subprocess.run(["git", "commit", "-qm", "later"], cwd=repo, env=env,
                   check=True, capture_output=True)
    newer = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=repo, env=env, check=True,
        capture_output=True, text=True).stdout.strip()
    # Re-point the prepared worktree at the wrong commit.
    subprocess.run(["git", "checkout", "-q", newer], cwd=ws["prepared_worktree"],
                   env=env, check=True, capture_output=True)
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []


def test_prepared_worktree_dirty_refused(board, tmp_path, dispatch_policy):
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    Path(ws["prepared_worktree"], "stray.txt").write_text("unexpected\n")
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []
    # Partial/foreign state is preserved — never reset.
    assert Path(ws["prepared_worktree"], "stray.txt").is_file()


def test_prepared_worktree_foreign_repo_refused(
    board, tmp_path, dispatch_policy, git_repo
):
    db, bridge = board
    data, rev = dispatch_policy
    repo, _rev = git_repo
    # A git worktree of a DIFFERENT repository at the same base is foreign.
    other = tmp_path / "other-repo"
    subprocess.run(["git", "init", "-q", str(other)], check=True,
                   capture_output=True)
    env = dict(os.environ, GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t",
               GIT_COMMITTER_NAME="t", GIT_COMMITTER_EMAIL="t@t")
    Path(other, "x.txt").write_text("x\n")
    subprocess.run(["git", "add", "-A"], cwd=other, env=env, check=True,
                   capture_output=True)
    subprocess.run(["git", "commit", "-qm", "x"], cwd=other, env=env,
                   check=True, capture_output=True)
    foreign = tmp_path / "foreign-wt"
    subprocess.run(
        ["git", "worktree", "add", "--quiet", "--detach", str(foreign), rev],
        cwd=other, env=env, check=False, capture_output=True,
    )
    ws = data["workspaces"]["ws-main"]
    ws["prepared_worktree"] = str(foreign)
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []


def test_binding_root_mismatch_refused(board, tmp_path, dispatch_policy):
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    # Binding points at a DIFFERENT directory than the prepared worktree.
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    ws["runner_execution_config"] = str(write_runner_config(
        tmp_path / "cfg2" / "exec.json",
        {"ws-alpha": {"root": str(elsewhere.resolve()),
                      "allowed_actions": [],
                      "allowed_presets": ["devin/swe-2-max"],
                      "allowed_models": None}},
    ))
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []


def test_binding_preset_not_allowed_refused(board, tmp_path, dispatch_policy):
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    ws["runner_execution_config"] = str(write_runner_config(
        tmp_path / "cfg3" / "exec.json",
        {"ws-alpha": {"root": ws["prepared_worktree"],
                      "allowed_actions": [],
                      "allowed_presets": ["mock/other"],   # ours is absent
                      "allowed_models": None}},
    ))
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []


def test_untrusted_runner_config_refused(board, tmp_path, dispatch_policy):
    db, bridge = board
    data, rev = dispatch_policy
    ws = data["workspaces"]["ws-main"]
    cfg = write_runner_config(
        tmp_path / "cfg4" / "exec.json",
        {"ws-alpha": {"root": ws["prepared_worktree"],
                      "allowed_actions": [],
                      "allowed_presets": ["devin/swe-2-max"],
                      "allowed_models": None}},
    )
    os.chmod(cfg, 0o644)  # group/other-readable -> untrusted
    ws["runner_execution_config"] = str(cfg)
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "blocked"
    assert client.calls == []


def test_gateway_mode_requires_control_base_url(tmp_path):
    """A gateway-mode execution target without a separate control target
    fails policy validation."""
    from cli_provider_kanban.policy import load_policy

    data = policy_dict()
    data["execution"] = {"mode": "gateway",
                         "base_url": "http://127.0.0.1:9"}
    path = write_policy(tmp_path, data)
    with pytest.raises(Exception):
        load_policy(path)


def test_gateway_submit_uses_route_combo(board, tmp_path, dispatch_policy):
    """Gateway mode must send the classifier route-derived combo name, never
    a static execution.model that bypasses classification."""
    db, bridge = board
    data, rev = dispatch_policy
    data["execution"] = {
        "mode": "gateway",
        "base_url": "http://127.0.0.1:9",
        "control_base_url": "http://127.0.0.1:9",
    }
    data["workspaces"]["ws-main"]["runner_execution_config"] = str(
        write_runner_config(
            tmp_path / "cfg5" / "exec.json",
            {"ws-alpha": {
                "root": data["workspaces"]["ws-main"]["prepared_worktree"],
                "allowed_actions": [],
                "allowed_presets": ["jev.worker.code.standard"],
                "allowed_models": None,
            }},
        )
    )
    tid = _card(bridge, tmp_path, data, rev)
    client = FakeWrapper()
    report, _ = _run(db, tmp_path, data, client)
    rec = _result(report, tid)
    assert rec["action"] == "review", rec
    assert client.calls[0]["model"] == "jev.worker.code.standard"
